version: 2.1
jobs:
  firstb:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  secondb:
  docker:
    - image: alpine:3.15
  steps:
    - run:
        name: The First Step
        command: |
          echo 'Hello World!'
          echo 'Double trouble!'
workflows:
  version: 2
  firstb_secondb:
    jobs:
      - firstb
      - secondb