export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_SOCIALS_PENDING = 'REQUEST_SOCIALS_PENDING';
export const REQUEST_SOCIALS_SUCCESS = 'REQUEST_SOCIALS_SUCCESS';
export const REQUEST_SOCIALS_FAILED = 'REQUEST_SOCIALS_FAILED';